### ISSUE TITLE
undefined error? 

### ISSUE THREAD

**Issue by rbrutoniii** [aleckeller/MMM-HappyHours#2]
{
			module: 'MMM-HappyHours',
			position: 'bottom_right',
			config: {
				state: 'us_ca',
				city: 'campbell'
			}
		}

There is my config - I'm getting an undefined(-1) error. Any ideas?

**Comment by aleckeller** [comment]
Yeah it looks like the website that's pulling the happy hours information uses campbell-1 instead of just campbell. So if you add that -1 for your city, it should resolve that error. If you ever have that problem again for another city, go to this URL http://thehappyhourfinder.com/{insert state}/all/, find and click on your city, then check the URL to see what the city name should be.

**Comment by rbrutoniii** [comment]
Missed the original email damnit. Figured it out myself eventually.


Thanks a lot though - great module!
